spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/sample
    username: sample_user
    password: sample_password
  data.solr.host: http://localhost:8983/solr
  mail:
    host: 127.0.0.1
    port: 25
    username: test
    password: test
    properties:
      mail:
        from: from@test.com
  flyway:
    enabled: true
    locations: classpath:/db/createTable,classpath:/db/insertData
    placeholderReplacement: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org.springframework: INFO
    org.springframework.jdbc: INFO
    org.thymeleaf: INFO
    com.isystk.sample: INFO

aws:
  s3:
    endpoint-url: "http://xxxxxxx"
    region: "ap-northeast-1"
    bucket-name: "/aws.isystk.com"
    profile-name: "isystk"

stripe:
  apiKey: "pk_xxxxxx"
  apiSecret: "sk_xxxxxx"
