spring:
  datasource:
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/laraec
    username: user
    password: password
  data.solr.host: http://localhost:8983/solr
  mail:
    host: 127.0.0.1
    port: 25
    username: test
    password: test
    properties:
      mail:
        from: no-reply@isystk.com
  flyway:
    baseline-on-migrate: true
    enabled: false
    locations: classpath:/db/createTable,classpath:/db/insertData
    placeholderReplacement: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "xxxxx"
            client-secret: "xxxxx"
            redirectUri: "http://localhost:8080/auth/google/loginSuccess"

logging:
  level:
    org.springframework: DEBUG
    org.springframework.jdbc: DEBUG
    org.thymeleaf: DEBUG
    com.isystk.sample: DEBUG

aws:
  s3:
    endpoint-url: "http://localhost:9000"
    region: "ap-northeast-1"
    bucket-name: "aws.isystk.com"
    #profile-name: "isystk"
    aws-access-key: "access_key"
    aws-secret-key: "secret_key"

stripe:
  apiKey: "pk_xxxxxx"
  apiSecret: "sk_xxxxxx"
