# 共通の設定を定義する
spring:
  profiles:
    production
  datasource:
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: password
  data.solr.host: http://localhost:8983/solr
  mail:
    host: 127.0.0.1
    port: 25
    username: test
    password: test
    properties:
      mail:
        from: from@test.com

logging:
  level:
    org.springframework: INFO
    org.springframework.jdbc: INFO
    org.thymeleaf: INFO
    com.isystk.sample: INFO
