
CREATE DATABASE IF NOT EXIST sample DEFAULT CHARACTER SET utf8mb4;

USE sample;

CREATE TABLE IF NOT EXISTS ITEM (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  name varchar(255),
  price real,
  vendor varchar(255),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS STAFF (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  EMAIL VARCHAR(64) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM STAFF WHERE email = 'test@sample.com';
INSERT INTO STAFF(email, password) VALUES
('test@sample.com', '$2a$06$hY5MzfruCds1t5uFLzrlBuw3HcrEGeysr9xJE4Cml5xEOVf425pmK');


